services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: anclora_rag
      POSTGRES_USER: anclora_user
      POSTGRES_PASSWORD: anclora_secure_pass_2025
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anclora_user -d anclora_rag"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6363:6333"
      - "6364:6334"
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    env_file:
      - "../../.env"
    volumes:
      - ../../apps/api:/app
      - ../../packages:/packages
      - ../../models:/models
      - ${USERPROFILE}/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8030:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    env_file:
      - "../../.env"
    volumes:
      - ../../apps/api:/app
      - ../../packages:/packages
      - ../../models:/models
      - ${USERPROFILE?err}/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      postgres:
        condition: service_healthy
    command: rq worker ingestion --url redis://redis:6379
    healthcheck:
      test: ["CMD", "rq", "info", "--url", "redis://redis:6379"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
